#version 450

#extension GL_GOOGLE_include_directive: require

#include "../config.hpp"

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

struct TileAABB {
    vec4 minPoint;
    vec4 maxPoint;
};

layout (std430, set = 3, binding = 0) buffer clusterAABBBuffer {
    TileAABB clusters[];
} ClusterAABB;

layout (std140, set = 3, binding = 1) uniform ClusterInfoBuffer {
    mat4 view;
    mat4 invProj;
    uvec4 tileSizes;
    uvec4 screen; // xy = dimensions, zw = near far
    uint noOfLights;
} ClusterInfo;

struct LightData {
    vec4 position; // xyz = pos, w = radius
    vec4 color;    // xyz = color, w = intensity
};

// xyz = pos, w = radius
// xyz = color, w = intensity
layout(std430, set = 0, binding = 1) readonly buffer LightsListBuffer {
    LightData lights[];
} LightsList;

layout(std430, set = 3,  binding = 2) buffer ClusterLightIndexListBuffer {
    uint lightIndices[]; // flattened light indices
} ClusterLightIndexList;

layout(std430, set = 3,  binding = 3) buffer ClusterLightCountsListBuffer {
    uint lightCounts[];
} ClusterLightCountsList;

float sqDistPointAABB(vec3 point, uint tile){
    float sqDist = 0.0;
    TileAABB currentCell = ClusterAABB.clusters[tile];
	for (uint i = 0; i < 3; ++i)
	{
		float v = point[i];
		if (v < currentCell.minPoint[i])
		{
			float diff = currentCell.minPoint[i] - v;
			sqDist += (diff * diff);
		}
		else if (v > currentCell.maxPoint[i])
		{
			float diff = currentCell.maxPoint[i] - v;
			sqDist += (diff * diff);
		}
	}

    return sqDist;
}

bool testSphereAABB(uint light, uint tile){
    float radius = LightsList.lights[light].position.w;
    vec3 center  = vec3(ClusterInfo.view * vec4(LightsList.lights[light].position.xyz, 1.0));
    float squaredDistance = sqDistPointAABB(center, tile);

    return squaredDistance < (radius * radius);
}

shared uint sharedIndices[MAX_LIGHTS_PER_CLUSTER];
shared uint sharedCount;

void main(){
	uint tileIndex =
		gl_WorkGroupID.x +
		gl_WorkGroupID.y * gl_NumWorkGroups.x +
		gl_WorkGroupID.z * gl_NumWorkGroups.x * gl_NumWorkGroups.y;

	uint localIndex = gl_LocalInvocationID.x;
	uint stride = gl_WorkGroupSize.x;

	if(localIndex == 0)
		sharedCount = 0;

	barrier();

	for (uint i = localIndex; i < ClusterInfo.noOfLights; i += stride) {
		if (testSphereAABB(i, tileIndex)) {
		uint index = atomicAdd(sharedCount, 1); 
		if (index < MAX_LIGHTS_PER_CLUSTER) 
			sharedIndices[index] = i;
		}
	}

	barrier();

	if(localIndex == 0) {
		uint count = min(sharedCount, MAX_LIGHTS_PER_CLUSTER);
		uint offset = tileIndex * MAX_LIGHTS_PER_CLUSTER;
		for(int i = 0; i < count; i++) {
			ClusterLightIndexList.lightIndices[offset + i] = sharedIndices[i];
		}

		ClusterLightCountsList.lightCounts[tileIndex] = count;
	}

}