#version 430 core
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#define MAX_LIGHTS_PER_CLUSTER 128

struct TileAABB {
    vec4 minPoint;
    vec4 maxPoint;
};

layout (std430, set = 3, binding = 0) buffer clusterAABBBuffer {
    TileAABB clusters[];
} ClusterAABB;

layout (std140, set = 3, binding = 1) uniform ClusterInfoBuffer {
    mat4 view;
    mat4 invProj;
    uvec4 tileSizes;
    uvec4 screen; // xy = dimensions, zw = near far
} ClusterInfo;

vec4 ClipToView(vec4 clip) {
    //View space transform
    vec4 view = ClusterInfo.invProj * clip;

    //Perspective projection
    view = view / view.w;
    
    return view;
}

vec4 ScreenToView(vec2 screen) {
    //Convert to NDC
    //vec2 texCoord = screen / ClusterInfo.screen.xy;

    //Convert to clipSpace
    // vec4 clip = vec4(vec2(texCoord.x, 1.0 - texCoord.y)* 2.0 - 1.0, 0.0, 1.0);
    vec4 clip = vec4(screen * 2.0 - 1.0, 0.0, 1.0);

    return ClipToView(clip);
}

vec3 LineIntersectionToZPlane(vec3 A, vec3 B, float zDistance) {
    //Because this is a Z based normal this is fixed
    vec3 normal = vec3(0.0, 0.0, 1.0);

    vec3 ab =  B - A;

    //Computing the intersection length for the line and the plane
    float t = (zDistance - dot(normal, A)) / dot(normal, ab);

    //Computing the actual xyz position of the point along the line
    vec3 result = A + t * ab;

    return result;
}

void main() {
    const vec3 eyePos = vec3(0.0);

    float zNear = ClusterInfo.screen.z;
    float zFar  = ClusterInfo.screen.w;

    uint tileIndex = gl_WorkGroupID.x +
                     gl_WorkGroupID.y * gl_NumWorkGroups.x +
                     gl_WorkGroupID.z * (gl_NumWorkGroups.x * gl_NumWorkGroups.y);

	vec2 normPerTileSize = vec2(1.0 / float(ClusterInfo.tileSizes.x),
		1.0 / float(ClusterInfo.tileSizes.y));

    vec2 maxPoint_SS = vec2(gl_WorkGroupID.xy + 1) * normPerTileSize;
    vec2 minPoint_SS = gl_WorkGroupID.xy * normPerTileSize;

    vec3 maxPoint_VS = ScreenToView(maxPoint_SS).xyz;
    vec3 minPoint_VS = ScreenToView(minPoint_SS).xyz;

    float tileNear = -zNear * pow(zFar/zNear, gl_WorkGroupID.z/float(gl_NumWorkGroups.z));
    float tileFar  = -zNear * pow(zFar/zNear, (gl_WorkGroupID.z + 1)/float(gl_NumWorkGroups.z));

    vec3 minPointNear = LineIntersectionToZPlane(eyePos, minPoint_VS, tileNear);
    vec3 minPointFar  = LineIntersectionToZPlane(eyePos, minPoint_VS, tileFar);
    vec3 maxPointNear = LineIntersectionToZPlane(eyePos, maxPoint_VS, tileNear);
    vec3 maxPointFar  = LineIntersectionToZPlane(eyePos, maxPoint_VS, tileFar);

    vec3 minPointAABB = min(min(minPointNear, minPointFar),min(maxPointNear, maxPointFar));
    vec3 maxPointAABB = max(max(minPointNear, minPointFar),max(maxPointNear, maxPointFar));

    ClusterAABB.clusters[tileIndex].minPoint  = vec4(minPointAABB , 0.0);
    ClusterAABB.clusters[tileIndex].maxPoint  = vec4(maxPointAABB , 0.0);
}