#version 450
layout(local_size_x = 16, local_size_y = 9, local_size_z = 4) in;

#define MAX_LIGHTS 2048
#define MAX_LIGHTS_PER_CLUSTER 128

#define NUM_CLUSTERS_X 1
#define NUM_CLUSTERS_Y 1
#define NUM_CLUSTERS_Z 6

struct TileAABB {
    vec4 minPoint;
    vec4 maxPoint;
};

layout (std430, set = 5, binding = 0) buffer Clusters{
    TileAABB clusters[];
} ssbo_ClusterAABB;

layout(set = 5, binding = 1) uniform ClusterInfo {
    mat4 view;  
    mat4 invProj;
    uvec4 tileSizes;
    vec2 screenDimensions;
    float zNear;
    float zFar;
    uint numLights;
    uint _padding0;
} u_ClusterInfo;

struct LightData {
    vec4 position; // xyz = pos, w = radius
    vec4 color;    // xyz = color, w = intensity
};

// xyz = pos, w = radius
// xyz = color, w = intensity
layout(std430, set = 1, binding = 0) readonly buffer LightsList {
    LightData lights[MAX_LIGHTS];
} ssbo_LightsList;

layout(std430, set = 5,  binding = 2) buffer ClusterLightIndexList {
    uint lightIndices[]; // flattened light indices
} ssbo_ClusterLightIndexList;

layout(std430, set = 5,  binding = 3) buffer ClusterLightOffsetList {
    uvec2 lightOffsets[]; // start, count per cluster
} ssbo_ClusterLightOffsetList;

// atomic counter for each cluster
layout(std430, set = 5,  binding = 4) buffer AtomicCounters {
    uint counters[];
} ssbo_AtomicCounters;

layout (std430, set = 5, binding = 5) buffer GlobalIndexCount {
    uint globalIndexCount;
} ssbo_GlobalIndex;

float sqDistPointAABB(vec3 point, uint tile){
    float sqDist = 0.0;
    TileAABB currentCell = ssbo_ClusterAABB.clusters[tile];
	for (uint i = 0; i < 3; ++i)
	{
		float v = point[i];
		if (v < currentCell.minPoint[i])
		{
			float diff = currentCell.minPoint[i] - v;
			sqDist += (diff * diff);
		}
		else if (v > currentCell.maxPoint[i])
		{
			float diff = currentCell.maxPoint[i] - v;
			sqDist += (diff * diff);
		}
	}

    return sqDist;
}

bool testSphereAABB(uint light, uint tile){
    float radius = ssbo_LightsList.lights[light].position.w;
    vec3 center  = vec3(ssbo_LightsList.lights[light].position);
    float squaredDistance = sqDistPointAABB(center, tile);

    return squaredDistance < (radius * radius);
}

shared LightData sharedLights[16*9*4];

void main()
{
	ssbo_GlobalIndex.globalIndexCount = 0;
	uint threadCount = gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z;
	uint lightCount = MAX_LIGHTS;
	uint numBatches = (lightCount + threadCount - 1) / threadCount;

	uint tileIndex = gl_LocalInvocationIndex + gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z * gl_WorkGroupID.z;

	uint visibleLightCount = 0;
    uint visibleLightIndices[MAX_LIGHTS_PER_CLUSTER];

    for(uint batch = 0; batch < numBatches; ++batch){
        uint lightIndex = batch * threadCount + gl_LocalInvocationIndex;

        //Prevent overflow by clamping to last light which is always null
        lightIndex = min(lightIndex, lightCount - 1);

        //Populating shared light array
        sharedLights[gl_LocalInvocationIndex] = ssbo_LightsList.lights[lightIndex];
        barrier();

        //Iterating within the current batch of lights
        for(uint light = 0; light < threadCount; ++light){
            //if(sharedLights[light].enabled  == 1)
            if(true){
                if(testSphereAABB(light, tileIndex)){
                    visibleLightIndices[visibleLightCount] = batch * threadCount + light;
                    visibleLightCount += 1;
                }
            }
        }
    }

    barrier();

    uint offset = atomicAdd(ssbo_GlobalIndex.globalIndexCount, visibleLightCount);

    for(uint i = 0; i < visibleLightCount; ++i){
        ssbo_ClusterLightIndexList.lightIndices[offset + i] = visibleLightIndices[i];
    }

    ssbo_ClusterLightOffsetList.lightOffsets[tileIndex].x = offset;
    ssbo_ClusterLightOffsetList.lightOffsets[tileIndex].y = visibleLightCount;
}