#version 450
#define LOCAL_SIZE 128
layout(local_size_x = LOCAL_SIZE, local_size_y = 1, local_size_z = 1) in;

#define MAX_LIGHTS 1024
#define MAX_LIGHTS_PER_CLUSTER 128

struct TileAABB {
    vec4 minPoint;
    vec4 maxPoint;
    uint count;
    uint lightIndices[MAX_LIGHTS_PER_CLUSTER];
};

layout (std430, set = 5, binding = 0) buffer Clusters{
    TileAABB clusters[];
} ssbo_ClusterAABB;

layout(set = 5, binding = 1) uniform ClusterInfo {
    mat4 view;  
    mat4 invProj;
    uvec4 tileSizes;
    vec2 screenDimensions;
    float zNear;
    float zFar;
    uint numLights;
    uint _padding0;
} u_ClusterInfo;

struct LightData {
    vec4 position; // xyz = pos, w = radius
    vec4 color;    // xyz = color, w = intensity
};

// xyz = pos, w = radius
// xyz = color, w = intensity
layout(std430, set = 1, binding = 0) readonly buffer LightsList {
    LightData lights[MAX_LIGHTS];
} ssbo_LightsList;

layout(std430, set = 5,  binding = 2) buffer ClusterLightIndexList {
    uint lightIndices[]; // flattened light indices
} ssbo_ClusterLightIndexList;

layout(std430, set = 5,  binding = 3) buffer ClusterLightOffsetList {
    uvec2 lightOffsets[]; // start, count per cluster
} ssbo_ClusterLightOffsetList;

// atomic counter for each cluster
layout(std430, set = 5,  binding = 4) buffer AtomicCounters {
    uint counters[];
} ssbo_AtomicCounters;

layout (std430, set = 5, binding = 5) buffer GlobalIndexCount {
    uint globalIndexCount;
} ssbo_GlobalIndex;

shared LightData sharedLights[16*9*4];


bool testSphereAABB(uint i, TileAABB c);

void main()
{
    uint lightCount = 1024;
    uint index = gl_WorkGroupID.x * LOCAL_SIZE + gl_LocalInvocationID.x;
    TileAABB cluster = ssbo_ClusterAABB.clusters[index];

    // we need to reset count because culling runs every frame.
    // otherwise it would accumulate.
    cluster.count = 0;

    for (uint i = 0; i < lightCount; ++i)
    {
        if (testSphereAABB(i, cluster) && cluster.count < MAX_LIGHTS_PER_CLUSTER)
        {
            cluster.lightIndices[cluster.count] = i;
            cluster.count++;
        }
    }
    ssbo_ClusterAABB.clusters[index] = cluster;
}

bool sphereAABBIntersection(vec3 center, float radius, vec3 aabbMin, vec3 aabbMax)
{
    // closest point on the AABB to the sphere center
    vec3 closestPoint = clamp(center, aabbMin, aabbMax);
    // squared distance between the sphere center and closest point
    float distanceSquared = dot(closestPoint - center, closestPoint - center);
    return distanceSquared <= radius * radius;
}

// this just unpacks data for sphereAABBIntersection
bool testSphereAABB(uint i, TileAABB cluster)
{
    vec3 center = vec3(u_ClusterInfo.view * ssbo_LightsList.lights[i].position);
    float radius = ssbo_LightsList.lights[i].position.w;

    vec3 aabbMin = cluster.minPoint.xyz;
    vec3 aabbMax = cluster.maxPoint.xyz;

    return sphereAABBIntersection(center, radius, aabbMin, aabbMax);
}