
#define MAX_LIGHTS_PER_CLUSTER 128
#define MAX_LIGHTS 8192
#define MAX_LIGHTS_PER_CLUSTER 128

#define MESH_MAXVTX 64
#define MESH_MAXTRI 96
#define MESH_WGSIZE 64

#define NUM_CLUSTERS_X 16
#define NUM_CLUSTERS_Y 9
#define NUM_CLUSTERS_Z 24
#define NUM_TOTAL_CLUSTERS (NUM_CLUSTERS_X * NUM_CLUSTERS_Y * NUM_CLUSTERS_Z)

#define ScreenX 1920.0
#define ScreenY 1080.0
#define NearZ 1.0
#define FarZ 1000.0

#define NUM_CASCADES 4