#pragma once

#include <memory>

namespace Brisk 
{
	class Renderer {
	public:
		enum VkVertexInputRate {
			VERTEX_INPUT_RATE_VERTEX = 0,
			VERTEX_INPUT_RATE_INSTANCE = 1,
		};
		enum Format {
            FORMAT_UNDEFINED = 0,
            FORMAT_R4G4_UNORM_PACK8 = 1,
            FORMAT_R4G4B4A4_UNORM_PACK16 = 2,
            FORMAT_B4G4R4A4_UNORM_PACK16 = 3,
            FORMAT_R5G6B5_UNORM_PACK16 = 4,
            FORMAT_B5G6R5_UNORM_PACK16 = 5,
            FORMAT_R5G5B5A1_UNORM_PACK16 = 6,
            FORMAT_B5G5R5A1_UNORM_PACK16 = 7,
            FORMAT_A1R5G5B5_UNORM_PACK16 = 8,
            FORMAT_R8_UNORM = 9,
            FORMAT_R8_SNORM = 10,
            FORMAT_R8_USCALED = 11,
            FORMAT_R8_SSCALED = 12,
            FORMAT_R8_UINT = 13,
            FORMAT_R8_SINT = 14,
            FORMAT_R8_SRGB = 15,
            FORMAT_R8G8_UNORM = 16,
            FORMAT_R8G8_SNORM = 17,
            FORMAT_R8G8_USCALED = 18,
            FORMAT_R8G8_SSCALED = 19,
            FORMAT_R8G8_UINT = 20,
            FORMAT_R8G8_SINT = 21,
            FORMAT_R8G8_SRGB = 22,
            FORMAT_R8G8B8_UNORM = 23,
            FORMAT_R8G8B8_SNORM = 24,
            FORMAT_R8G8B8_USCALED = 25,
            FORMAT_R8G8B8_SSCALED = 26,
            FORMAT_R8G8B8_UINT = 27,
            FORMAT_R8G8B8_SINT = 28,
            FORMAT_R8G8B8_SRGB = 29,
            FORMAT_B8G8R8_UNORM = 30,
            FORMAT_B8G8R8_SNORM = 31,
            FORMAT_B8G8R8_USCALED = 32,
            FORMAT_B8G8R8_SSCALED = 33,
            FORMAT_B8G8R8_UINT = 34,
            FORMAT_B8G8R8_SINT = 35,
            FORMAT_B8G8R8_SRGB = 36,
            FORMAT_R8G8B8A8_UNORM = 37,
            FORMAT_R8G8B8A8_SNORM = 38,
            FORMAT_R8G8B8A8_USCALED = 39,
            FORMAT_R8G8B8A8_SSCALED = 40,
            FORMAT_R8G8B8A8_UINT = 41,
            FORMAT_R8G8B8A8_SINT = 42,
            FORMAT_R8G8B8A8_SRGB = 43,
            FORMAT_B8G8R8A8_UNORM = 44,
            FORMAT_B8G8R8A8_SNORM = 45,
            FORMAT_B8G8R8A8_USCALED = 46,
            FORMAT_B8G8R8A8_SSCALED = 47,
            FORMAT_B8G8R8A8_UINT = 48,
            FORMAT_B8G8R8A8_SINT = 49,
            FORMAT_B8G8R8A8_SRGB = 50,
            FORMAT_A8B8G8R8_UNORM_PACK32 = 51,
            FORMAT_A8B8G8R8_SNORM_PACK32 = 52,
            FORMAT_A8B8G8R8_USCALED_PACK32 = 53,
            FORMAT_A8B8G8R8_SSCALED_PACK32 = 54,
            FORMAT_A8B8G8R8_UINT_PACK32 = 55,
            FORMAT_A8B8G8R8_SINT_PACK32 = 56,
            FORMAT_A8B8G8R8_SRGB_PACK32 = 57,
            FORMAT_A2R10G10B10_UNORM_PACK32 = 58,
            FORMAT_A2R10G10B10_SNORM_PACK32 = 59,
            FORMAT_A2R10G10B10_USCALED_PACK32 = 60,
            FORMAT_A2R10G10B10_SSCALED_PACK32 = 61,
            FORMAT_A2R10G10B10_UINT_PACK32 = 62,
            FORMAT_A2R10G10B10_SINT_PACK32 = 63,
            FORMAT_A2B10G10R10_UNORM_PACK32 = 64,
            FORMAT_A2B10G10R10_SNORM_PACK32 = 65,
            FORMAT_A2B10G10R10_USCALED_PACK32 = 66,
            FORMAT_A2B10G10R10_SSCALED_PACK32 = 67,
            FORMAT_A2B10G10R10_UINT_PACK32 = 68,
            FORMAT_A2B10G10R10_SINT_PACK32 = 69,
            FORMAT_R16_UNORM = 70,
            FORMAT_R16_SNORM = 71,
            FORMAT_R16_USCALED = 72,
            FORMAT_R16_SSCALED = 73,
            FORMAT_R16_UINT = 74,
            FORMAT_R16_SINT = 75,
            FORMAT_R16_SFLOAT = 76,
            FORMAT_R16G16_UNORM = 77,
            FORMAT_R16G16_SNORM = 78,
            FORMAT_R16G16_USCALED = 79,
            FORMAT_R16G16_SSCALED = 80,
            FORMAT_R16G16_UINT = 81,
            FORMAT_R16G16_SINT = 82,
            FORMAT_R16G16_SFLOAT = 83,
            FORMAT_R16G16B16_UNORM = 84,
            FORMAT_R16G16B16_SNORM = 85,
            FORMAT_R16G16B16_USCALED = 86,
            FORMAT_R16G16B16_SSCALED = 87,
            FORMAT_R16G16B16_UINT = 88,
            FORMAT_R16G16B16_SINT = 89,
            FORMAT_R16G16B16_SFLOAT = 90,
            FORMAT_R16G16B16A16_UNORM = 91,
            FORMAT_R16G16B16A16_SNORM = 92,
            FORMAT_R16G16B16A16_USCALED = 93,
            FORMAT_R16G16B16A16_SSCALED = 94,
            FORMAT_R16G16B16A16_UINT = 95,
            FORMAT_R16G16B16A16_SINT = 96,
            FORMAT_R16G16B16A16_SFLOAT = 97,
            FORMAT_R32_UINT = 98,
            FORMAT_R32_SINT = 99,
            FORMAT_R32_SFLOAT = 100,
            FORMAT_R32G32_UINT = 101,
            FORMAT_R32G32_SINT = 102,
            FORMAT_R32G32_SFLOAT = 103,
            FORMAT_R32G32B32_UINT = 104,
            FORMAT_R32G32B32_SINT = 105,
            FORMAT_R32G32B32_SFLOAT = 106,
            FORMAT_R32G32B32A32_UINT = 107,
            FORMAT_R32G32B32A32_SINT = 108,
            FORMAT_R32G32B32A32_SFLOAT = 109,
            FORMAT_R64_UINT = 110,
            FORMAT_R64_SINT = 111,
            FORMAT_R64_SFLOAT = 112,
            FORMAT_R64G64_UINT = 113,
            FORMAT_R64G64_SINT = 114,
            FORMAT_R64G64_SFLOAT = 115,
            FORMAT_R64G64B64_UINT = 116,
            FORMAT_R64G64B64_SINT = 117,
            FORMAT_R64G64B64_SFLOAT = 118,
            FORMAT_R64G64B64A64_UINT = 119,
            FORMAT_R64G64B64A64_SINT = 120,
            FORMAT_R64G64B64A64_SFLOAT = 121,
            FORMAT_B10G11R11_UFLOAT_PACK32 = 122,
            FORMAT_E5B9G9R9_UFLOAT_PACK32 = 123,
            FORMAT_D16_UNORM = 124,
            FORMAT_X8_D24_UNORM_PACK32 = 125,
            FORMAT_D32_SFLOAT = 126,
            FORMAT_S8_UINT = 127,
            FORMAT_D16_UNORM_S8_UINT = 128,
            FORMAT_D24_UNORM_S8_UINT = 129,
            FORMAT_D32_SFLOAT_S8_UINT = 130,
            FORMAT_BC1_RGB_UNORM_BLOCK = 131,
            FORMAT_BC1_RGB_SRGB_BLOCK = 132,
            FORMAT_BC1_RGBA_UNORM_BLOCK = 133,
            FORMAT_BC1_RGBA_SRGB_BLOCK = 134,
            FORMAT_BC2_UNORM_BLOCK = 135,
            FORMAT_BC2_SRGB_BLOCK = 136,
            FORMAT_BC3_UNORM_BLOCK = 137,
            FORMAT_BC3_SRGB_BLOCK = 138,
            FORMAT_BC4_UNORM_BLOCK = 139,
            FORMAT_BC4_SNORM_BLOCK = 140,
            FORMAT_BC5_UNORM_BLOCK = 141,
            FORMAT_BC5_SNORM_BLOCK = 142,
            FORMAT_BC6H_UFLOAT_BLOCK = 143,
            FORMAT_BC6H_SFLOAT_BLOCK = 144,
            FORMAT_BC7_UNORM_BLOCK = 145,
            FORMAT_BC7_SRGB_BLOCK = 146,
            FORMAT_ETC2_R8G8B8_UNORM_BLOCK = 147,
            FORMAT_ETC2_R8G8B8_SRGB_BLOCK = 148,
            FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK = 149,
            FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK = 150,
            FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK = 151,
            FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK = 152,
            FORMAT_EAC_R11_UNORM_BLOCK = 153,
            FORMAT_EAC_R11_SNORM_BLOCK = 154,
            FORMAT_EAC_R11G11_UNORM_BLOCK = 155,
            FORMAT_EAC_R11G11_SNORM_BLOCK = 156,
            FORMAT_ASTC_4x4_UNORM_BLOCK = 157,
            FORMAT_ASTC_4x4_SRGB_BLOCK = 158,
            FORMAT_ASTC_5x4_UNORM_BLOCK = 159,
            FORMAT_ASTC_5x4_SRGB_BLOCK = 160,
            FORMAT_ASTC_5x5_UNORM_BLOCK = 161,
            FORMAT_ASTC_5x5_SRGB_BLOCK = 162,
            FORMAT_ASTC_6x5_UNORM_BLOCK = 163,
            FORMAT_ASTC_6x5_SRGB_BLOCK = 164,
            FORMAT_ASTC_6x6_UNORM_BLOCK = 165,
            FORMAT_ASTC_6x6_SRGB_BLOCK = 166,
            FORMAT_ASTC_8x5_UNORM_BLOCK = 167,
            FORMAT_ASTC_8x5_SRGB_BLOCK = 168,
            FORMAT_ASTC_8x6_UNORM_BLOCK = 169,
            FORMAT_ASTC_8x6_SRGB_BLOCK = 170,
            FORMAT_ASTC_8x8_UNORM_BLOCK = 171,
            FORMAT_ASTC_8x8_SRGB_BLOCK = 172,
            FORMAT_ASTC_10x5_UNORM_BLOCK = 173,
            FORMAT_ASTC_10x5_SRGB_BLOCK = 174,
            FORMAT_ASTC_10x6_UNORM_BLOCK = 175,
            FORMAT_ASTC_10x6_SRGB_BLOCK = 176,
            FORMAT_ASTC_10x8_UNORM_BLOCK = 177,
            FORMAT_ASTC_10x8_SRGB_BLOCK = 178,
            FORMAT_ASTC_10x10_UNORM_BLOCK = 179,
            FORMAT_ASTC_10x10_SRGB_BLOCK = 180,
            FORMAT_ASTC_12x10_UNORM_BLOCK = 181,
            FORMAT_ASTC_12x10_SRGB_BLOCK = 182,
            FORMAT_ASTC_12x12_UNORM_BLOCK = 183,
            FORMAT_ASTC_12x12_SRGB_BLOCK = 184,
		};
        enum SampleCount {
            SAMPLE_COUNT_1_BIT,
            SAMPLE_COUNT_2_BIT,
            SAMPLE_COUNT_4_BIT,
            SAMPLE_COUNT_8_BIT,
            SAMPLE_COUNT_16_BIT,
            SAMPLE_COUNT_32_BIT,
            SAMPLE_COUNT_64_BIT,
        };

        enum LoadOp {
            LOAD_OP_LOAD = 0,
            LOAD_OP_CLEAR = 1,
            LOAD_OP_DONT_CARE = 2,
            LOAD_OP_NONE = 3,
        };

        enum StoreOp {
            STORE_OP_STORE = 0,
            STORE_OP_DONT_CARE = 1,
            STORE_OP_NONE = 2,
        };

        enum ImageLayout {
            IMAGE_LAYOUT_UNDEFINED,
            IMAGE_LAYOUT_GENERAL,
            IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
            IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
            IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
            IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
            IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
            IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
            IMAGE_LAYOUT_PREINITIALIZED,
            IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
            IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
            IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
            IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
            IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
            IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
            IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
            IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
            IMAGE_LAYOUT_PRESENT_SRC_KHR,
            IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR,
            IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR,
            IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR,
            IMAGE_LAYOUT_SHARED_PRESENT_KHR,
            IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
            IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
            IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR,
            IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR,
            IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR,
            IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR,
            IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT,
        };

        struct Attachment {
            Format pFormat;
            SampleCount pSamples;
            LoadOp pLoadOp;
            StoreOp pStoreOp;
            LoadOp pStencilLoadOp;
            StoreOp pStencilStoreOp;
            ImageLayout pInitialLayout;
            ImageLayout pFinalLayout;
        };

        struct AttachmentRef {
            uint32_t pIndex;
            Attachment pAttachment;
        };

        enum AccessMask {
            ACCESS_INDIRECT_COMMAND_READ_BIT,
            ACCESS_INDEX_READ_BIT,
            ACCESS_VERTEX_ATTRIBUTE_READ_BIT,
            ACCESS_UNIFORM_READ_BIT,
            ACCESS_INPUT_ATTACHMENT_READ_BIT,
            ACCESS_SHADER_READ_BIT,
            ACCESS_SHADER_WRITE_BIT,
            ACCESS_COLOR_ATTACHMENT_READ_BIT,
            ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
            ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT,
            ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
            ACCESS_TRANSFER_READ_BIT,
            ACCESS_TRANSFER_WRITE_BIT,
            ACCESS_HOST_READ_BIT,
            ACCESS_HOST_WRITE_BIT,
            ACCESS_MEMORY_READ_BIT,
            ACCESS_MEMORY_WRITE_BIT,
            ACCESS_NONE,
            ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT,
            ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT,
            ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT,
            ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT,
            ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT,
            ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR,
            ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR,
            ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT,
            ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR,
            ACCESS_COMMAND_PREPROCESS_READ_BIT_NV,
            ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV
        };

        enum StageMask {
            PIPELINE_STAGE_TOP_OF_PIPE_BIT,
            PIPELINE_STAGE_DRAW_INDIRECT_BIT,
            PIPELINE_STAGE_VERTEX_INPUT_BIT,
            PIPELINE_STAGE_VERTEX_SHADER_BIT,
            PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT,
            PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT,
            PIPELINE_STAGE_GEOMETRY_SHADER_BIT,
            PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
            PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
            PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
            PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
            PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            PIPELINE_STAGE_TRANSFER_BIT,
            PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
            PIPELINE_STAGE_HOST_BIT,
            PIPELINE_STAGE_ALL_GRAPHICS_BIT,
            PIPELINE_STAGE_ALL_COMMANDS_BIT,
            PIPELINE_STAGE_NONE,
            PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT,
            PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT,
            PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
            PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,
            PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT,
            PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,
            PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV,
            PIPELINE_STAGE_TASK_SHADER_BIT_EXT,
            PIPELINE_STAGE_MESH_SHADER_BIT_EXT,
        };


        struct SubpassDependency {
            bool pIsSrcExternal = false;
            bool pIsDstExternal = false;
            uint32_t pSrcSubpassIndex;
            uint32_t pDstSubpassIndex;
            std::vector<StageMask> pSrcStageMasks;
            std::vector<AccessMask> pSrcAccessMasks;
            std::vector<StageMask> pDstStageMasks;
            std::vector<AccessMask> pDstAccessMask;
        };

        struct Subpass {
            uint32_t pIndex;
            std::vector<AttachmentRef> pColorAttachments;
            AttachmentRef pDepthAttachment;
        };

        struct RenderPass {
            std::vector<Attachment> pAttachments;
            std::vector<Subpass> pSubpasses;
            std::vector<SubpassDependency> pDependencies;
        };

	public:
		virtual void Init();
		virtual void Destroy() = 0;

		static std::unique_ptr<Renderer> Create();
	};
}